common_urls_http = [
'http://www.youtube.com'
'http://www.facebook.com'
'http://www.baidu.com'
'http://www.yahoo.com'
'http://www.amazon.com'
'http://www.wikipedia.org'
'http://www.qq.com'
'http://www.google.co.in'
'http://www.twitter.com'
'http://www.live.com'
'http://www.taobao.com'
'http://www.bing.com'
'http://www.instagram.com'
'http://www.weibo.com'
'http://www.sina.com.cn'
'http://www.linkedin.com'
'http://www.yahoo.co.jp'
'http://www.msn.com'
'http://www.vk.com'
'http://www.google.de'
'http://www.yandex.ru'
'http://www.hao123.com'
'http://www.google.co.uk'
'http://www.reddit.com'
'http://www.ebay.com'
'http://www.google.fr'
'http://www.t.co'
'http://www.tmall.com'
'http://www.google.com.br'
'http://www.360.cn'
'http://www.sohu.com'
'http://www.amazon.co.jp'
'http://www.pinterest.com'
'http://www.netflix.com'
'http://www.google.it'
'http://www.google.ru'
'http://www.microsoft.com'
'http://www.google.es'
'http://www.wordpress.com'
'http://www.gmw.cn'
'http://www.tumblr.com'
'http://www.paypal.com'
'http://www.blogspot.com'
'http://www.imgur.com'
'http://www.stackoverflow.com'
'http://www.aliexpress.com'
'http://www.naver.com'
'http://www.ok.ru'
'http://www.apple.com'
'http://www.github.com'
'http://www.chinadaily.com.cn'
'http://www.imdb.com'
'http://www.google.co.kr'
'http://www.fc2.com'
'http://www.jd.com'
'http://www.blogger.com'
'http://www.163.com'
'http://www.google.ca'
'http://www.whatsapp.com'
'http://www.amazon.in'
'http://www.office.com'
'http://www.tianya.cn'
'http://www.google.co.id'
'http://www.youku.com'
'http://www.rakuten.co.jp'
'http://www.craigslist.org'
'http://www.amazon.de'
'http://www.nicovideo.jp'
'http://www.google.pl'
'http://www.soso.com'
'http://www.bilibili.com'
'http://www.dropbox.com'
'http://www.xinhuanet.com'
'http://www.outbrain.com'
'http://www.pixnet.net'
'http://www.alibaba.com'
'http://www.alipay.com'
'http://www.microsoftonline.com'
'http://www.booking.com'
'http://www.googleusercontent.com'
'http://www.google.com.au'
'http://www.popads.net'
'http://www.cntv.cn'
'http://www.zhihu.com'
'http://www.amazon.co.uk'
'http://www.diply.com'
'http://www.coccoc.com'
'http://www.cnn.com'
'http://www.bbc.co.uk'
'http://www.twitch.tv'
'http://www.wikia.com'
'http://www.google.co.th'
'http://www.go.com'
'http://www.google.com.ph'
'http://www.doubleclick.net'
'http://www.onet.pl'
'http://www.googleadservices.com'
'http://www.accuweather.com'
'http://www.googleweblight.com'
'http://www.answers.yahoo.com'
'http://www.sans.org'
]
common_urls_https = [
'https://www.youtube.com',
'https://www.facebook.com',
'https://www.baidu.com',
'https://www.yahoo.com',
'https://www.amazon.com',
'https://www.wikipedia.org',
'https://www.qq.com',
'https://www.google.co.in',
'https://www.twitter.com',
'https://www.live.com',
'https://www.taobao.com',
'https://www.bing.com',
'https://www.instagram.com',
'https://www.weibo.com',
'https://www.sina.com.cn',
'https://www.linkedin.com',
'https://www.yahoo.co.jp',
'https://www.msn.com',
'https://www.vk.com',
'https://www.google.de',
'https://www.yandex.ru',
'https://www.hao123.com',
'https://www.google.co.uk',
'https://www.reddit.com',
'https://www.ebay.com',
'https://www.google.fr',
'https://www.t.com',
'https://www.tmall.com',
'https://www.google.com.br',
'https://www.360.cn',
'https://www.sohu.com',
'https://www.amazon.co.jp',
'https://www.pinterest.com',
'https://www.netflix.com',
'https://www.google.it',
'https://www.google.ru',
'https://www.microsoft.com',
'https://www.google.es',
'https://www.wordpress.com',
'https://www.gmw.cn',
'https://www.tumblr.com',
'https://www.paypal.com',
'https://www.blogspot.com',
'https://www.imgur.com',
'https://www.stackoverflow.com',
'https://www.aliexpress.com',
'https://www.naver.com',
'https://www.ok.ru',
'https://www.apple.com',
'https://www.github.com',
'https://www.chinadaily.com.cn',
'https://www.imdb.com',
'https://www.google.co.kr',
'https://www.fc2.com',
'https://www.jd.com',
'https://www.blogger.com',
'https://www.163.com',
'https://www.google.ca',
'https://www.whatsapp.com',
'https://www.amazon.in',
'https://www.office.com',
'https://www.tianya.cn',
'https://www.google.co.id',
'https://www.youku.com',
'https://www.rakuten.co.jp',
'https://www.craigslist.org',
'https://www.amazon.de',
'https://www.nicovideo.jp',
'https://www.google.pl',
'https://www.soso.com',
'https://www.bilibili.com',
'https://www.dropbox.com',
'https://www.xinhuanet.com',
'https://www.outbrain.com',
'https://www.pixnet.net',
'https://www.alibaba.com',
'https://www.alipay.com',
'https://www.microsoftonline.com',
'https://www.booking.com',
'https://www.googleusercontent.com',
'https://www.google.com.au',
'https://www.popads.net',
'https://www.cntv.cn',
'https://www.zhihu.com',
'https://www.amazon.co.uk',
'https://www.diply.com',
'https://www.coccoc.com',
'https://www.cnn.com',
'https://www.bbc.co.uk',
'https://www.twitch.tv',
'https://www.wikia.com',
'https://www.google.co.th',
'https://www.go.com',
'https://www.google.com.ph',
'https://www.doubleclick.net',
'https://www.onet.pl',
'https://www.googleadservices.com',
'https://www.accuweather.com',
'https://www.googleweblight.com',
'https://www.answers.yahoo.com',
'https://www.sans.org',
'https://support.google.com',
'https://www.adobe.com',
'https://www.gulf-times.com',

]